#!/bin/bash

# ============================================================================
# Climate Bias Experiment - Firebase Setup Helper
# ============================================================================
# This script will help you configure Firebase credentials after you create
# your Firebase project.
#
# BEFORE running this script:
# 1. Go to https://console.firebase.google.com
# 2. Create a new project (name it whatever you like)
# 3. Enable Realtime Database (Test Mode)
# 4. Copy your config from: Project Settings → Web tab
# 5. Run this script and paste the values when prompted
# ============================================================================

echo ""
echo "╔════════════════════════════════════════════════════════════════════════╗"
echo "║     Climate Bias Experiment - Firebase Configuration Helper            ║"
echo "╚════════════════════════════════════════════════════════════════════════╝"
echo ""

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Not in the climate-project-app directory"
    echo "Please run this script from the climate-project-app folder:"
    echo "  cd climate-project-app && bash setup-firebase.sh"
    exit 1
fi

echo -e "${BLUE}STEP 1: Firebase Project Setup${NC}"
echo ""
echo "If you haven't already, go to: ${YELLOW}https://console.firebase.google.com${NC}"
echo ""
echo "Then follow these steps:"
echo "  1. Click 'Create a new project'"
echo "  2. Name it (example: 'climate-bias-experiment')"
echo "  3. Accept the defaults and click 'Create project'"
echo "  4. Wait for creation to complete"
echo ""
echo "Once created, enable Realtime Database:"
echo "  1. In left sidebar, click 'Realtime Database'"
echo "  2. Click 'Create Database'"
echo "  3. Select your region (closest to your users)"
echo "  4. Choose 'Start in Test Mode' (for development)"
echo "  5. Click 'Enable'"
echo ""
read -p "Press Enter when you've completed these steps..."
echo ""

echo -e "${BLUE}STEP 2: Get Your Firebase Credentials${NC}"
echo ""
echo "Now grab your config:"
echo "  1. Go to Project Settings (gear icon, top-left)"
echo "  2. Click the 'Web' tab"
echo "  3. You'll see a config object looking like this:"
echo ""
echo -e "${YELLOW}{"
echo "  apiKey: 'AIzaSyD...',"
echo "  authDomain: 'your-project.firebaseapp.com',"
echo "  databaseURL: 'https://your-project-default-rtdb.firebaseio.com',"
echo "  projectId: 'your-project',"
echo "  storageBucket: 'your-project.appspot.com',"
echo "  messagingSenderId: '123456789',"
echo "  appId: '1:123456789:web:abc...'"
echo "}${NC}"
echo ""
echo "Copy these values and provide them below:"
echo ""

# Collect Firebase credentials
read -p "Enter API Key: " API_KEY
read -p "Enter Auth Domain: " AUTH_DOMAIN
read -p "Enter Database URL: " DATABASE_URL
read -p "Enter Project ID: " PROJECT_ID
read -p "Enter Storage Bucket: " STORAGE_BUCKET
read -p "Enter Messaging Sender ID: " MESSAGING_SENDER_ID
read -p "Enter App ID: " APP_ID

echo ""
echo -e "${BLUE}STEP 3: Creating .env.local${NC}"
echo ""

# Create .env.local
cat > .env.local << EOF
# Firebase Realtime Database Configuration
# Generated by setup-firebase.sh on $(date)

NEXT_PUBLIC_FIREBASE_API_KEY=$API_KEY
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_DATABASE_URL=$DATABASE_URL
NEXT_PUBLIC_FIREBASE_PROJECT_ID=$PROJECT_ID
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$STORAGE_BUCKET
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$MESSAGING_SENDER_ID
NEXT_PUBLIC_FIREBASE_APP_ID=$APP_ID
EOF

echo -e "${GREEN}✓ Created .env.local${NC}"
echo ""

# Verify .env.local exists
if [ -f ".env.local" ]; then
    echo -e "${GREEN}✓ Configuration file created successfully${NC}"
    echo ""
    echo -e "${BLUE}STEP 4: Verify Configuration${NC}"
    echo ""
    echo "Your .env.local file contains:"
    echo ""
    grep "NEXT_PUBLIC_" .env.local | sed 's/=.*/=***REDACTED***/g'
    echo ""
    echo -e "${GREEN}✓ All environment variables configured${NC}"
    echo ""
else
    echo -e "${YELLOW}❌ Failed to create .env.local${NC}"
    exit 1
fi

echo ""
echo -e "${BLUE}STEP 5: Test Your Setup${NC}"
echo ""
echo "Now run the development server to test:"
echo ""
echo -e "${YELLOW}npm run dev${NC}"
echo ""
echo "Then:"
echo "  1. Open http://localhost:3000"
echo "  2. Complete the experiment"
echo "  3. Check Firebase console to see your response stored"
echo ""

echo -e "${GREEN}╔════════════════════════════════════════════════════════════════════════╗"
echo "║                    ✓ Firebase Setup Complete!                           ║"
echo "╚════════════════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "To test real-time sync:"
echo "  • Open experiment in two tabs/devices simultaneously"
echo "  • Complete a phase in one tab"
echo "  • Watch the results update live in the other tab (no refresh needed!)"
echo ""
